"""Benchmark the complete R Amelia pipeline with only EM replaced by PyTorch.

The default inputs are the exact, read-only CSVs already generated by the main
suite. No native-Python timings are substituted for R-user end-to-end timings.
Defaults: 100k rows, m=5, two warmups, five repetitions, four CPU threads, and
serial R replicate scheduling. Use --methods cpu64 cpu32 on a CPU-only host;
CUDA runs are opt-in with --methods cpu64 cpu32 cuda32 cuda64.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATASETS = ("covertype", "household_power", "year_prediction_msd")
METHODS = {
    "cpu64": ("cpu", "float64"),
    "cpu32": ("cpu", "float32"),
    "mps32": ("mps", "float32"),
    "cuda32": ("cuda", "float32"),
    "cuda64": ("cuda", "float64"),
}
THREAD_VARIABLES = (
    "OMP_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "MKL_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
)


def file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def inspect_csv(path: Path, expected_rows: int, expected_columns: list[str]) -> dict:
    """Check the main suite's simple CSV dimensions while streaming its digest."""
    digest = hashlib.sha256()
    newline_count = 0
    final_byte = b""
    with path.open("rb") as stream:
        header = stream.readline()
        if header.decode("utf-8").rstrip("\r\n").split(",") != expected_columns:
            raise ValueError(f"CSV columns differ from prepared metadata: {path.name}")
        digest.update(header)
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
            newline_count += chunk.count(b"\n")
            final_byte = chunk[-1:]
    rows = newline_count + int(bool(final_byte) and final_byte != b"\n")
    if rows != expected_rows:
        raise ValueError(
            f"CSV row count differs from requested {expected_rows}: {path.name} ({rows})"
        )
    return {
        "filename": path.name,
        "sha256": digest.hexdigest(),
        "rows": rows,
        "columns": len(expected_columns),
        "bytes": path.stat().st_size,
    }


def prepared_path(dataset: str, rows: int) -> Path:
    return ROOT / "data/prepared" / f"{dataset}-n{rows}-block_mcar-rate30-seed20260923.npz"


def generate_csvs(source: Path, dataset: str, destination: Path) -> None:
    """Use exactly the main suite's float serialization in a separate directory."""
    destination.mkdir(parents=True, exist_ok=True)
    with np.load(source, allow_pickle=False) as prepared:
        header = ",".join(prepared["column_names"])
        for field, name in (
            ("data", "input"),
            ("truth", "truth"),
            ("artificial_missing_mask", "mask"),
        ):
            path = destination / f"{dataset}-{name}.csv"
            temporary = path.with_name(path.name + ".tmp")
            if path.exists() or temporary.exists() or path.is_symlink() or temporary.is_symlink():
                raise FileExistsError(f"Refusing to overwrite generated CSV: {path.name}")
            np.savetxt(
                temporary,
                prepared[field],
                delimiter=",",
                header=header,
                comments="",
                fmt="%d" if name == "mask" else "%.17g",
            )
            os.replace(temporary, path)


def save_suite(path: Path, value: dict) -> None:
    temporary = path.with_name(path.name + ".tmp")
    if path.is_symlink() or temporary.is_symlink():
        raise ValueError("Refusing symbolic-link report destination")
    temporary.write_text(json.dumps(value, indent=2, allow_nan=False) + "\n")
    os.replace(temporary, path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "results/local/benchmarks/hybrid")
    parser.add_argument(
        "--csv-dir",
        type=Path,
        default=ROOT / "results/local/benchmarks/main/inputs",
        help="Existing main-suite inputs; always read-only",
    )
    parser.add_argument(
        "--generate-inputs",
        action="store_true",
        help="Generate separate CSVs inside output-dir/inputs from the same NPZs",
    )
    parser.add_argument("--datasets", nargs="+", choices=DATASETS, default=list(DATASETS))
    parser.add_argument(
        "--methods", nargs="+", choices=METHODS, default=["cpu64", "cpu32", "mps32"]
    )
    parser.add_argument("--rows", type=int, default=100000)
    parser.add_argument("--m", type=int, default=5)
    parser.add_argument("--repeats", type=int, default=5)
    parser.add_argument("--warmups", type=int, default=2)
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--seed", type=int, default=20260923)
    parser.add_argument("--warmup-seed", type=int, default=20360923)
    parser.add_argument("--order-seed", type=int, default=20260923)
    parser.add_argument("--max-iterations", type=int, default=300)
    parser.add_argument(
        "--timeout-seconds",
        type=float,
        default=3600,
        help="Per dataset/method process timeout; failures remain in suite.json",
    )
    parser.add_argument("--rscript", default="Rscript")
    parser.add_argument(
        "--plan-only",
        action="store_true",
        help="Print intended tasks without writing files, importing torch or fitting",
    )
    args = parser.parse_args()
    if (
        min(args.rows, args.m, args.repeats, args.threads) < 1
        or args.warmups < 0
        or args.max_iterations < 1
        or args.timeout_seconds <= 0
    ):
        parser.error("Counts/threads/iteration limit/timeout must be positive; warmups may be zero")
    if len(set(args.datasets)) != len(args.datasets) or len(set(args.methods)) != len(args.methods):
        parser.error("Do not repeat dataset or method IDs")
    generator = random.Random(args.order_seed)
    plan = []
    for dataset in args.datasets:
        methods = list(args.methods)
        generator.shuffle(methods)
        for method in methods:
            device, dtype = METHODS[method]
            plan.append({"dataset": dataset, "method": method, "device": device, "dtype": dtype})
    if args.plan_only:
        print(
            json.dumps(
                {
                    "plan_only": True,
                    "rows": args.rows,
                    "m": args.m,
                    "warmups": args.warmups,
                    "repetitions": args.repeats,
                    "threads": args.threads,
                    "parallel": "no",
                    "ncpus": 1,
                    "tasks": plan,
                },
                indent=2,
            )
        )
        return 0
    args.output_dir.mkdir(parents=True, exist_ok=True)
    suite_path = args.output_dir / "suite.json"
    if suite_path.exists():
        parser.error("Output suite.json already exists; choose a fresh output directory")
    sources = [
        *sorted((ROOT / "src/amelia_torch").glob("*.py")),
        *sorted((ROOT / "r-package/R").glob("*.R")),
        *sorted((ROOT / "r-package/src").glob("*.c")),
        ROOT / "r-package/DESCRIPTION",
        ROOT / "r-package/NAMESPACE",
        ROOT / "scripts/benchmark_hybrid.R",
        Path(__file__).resolve(),
    ]
    source_hashes = {str(path.relative_to(ROOT)): file_hash(path) for path in sources}
    suite = {
        "schema_version": 1,
        "created_utc": datetime.now(UTC).isoformat(),
        "description": "Original R Amelia pipeline with only EM replaced by PyTorch; full R-user end-to-end calls, serial replicate scheduling",
        "settings": {
            "rows": args.rows,
            "m": args.m,
            "warmups": args.warmups,
            "repeats": args.repeats,
            "threads": args.threads,
            "tolerance": 1e-4,
            "emburn": [0, args.max_iterations],
            "empri": None,
            "autopri": 0.05,
            "startvals": 0,
            "boot.type": "ordinary",
            "parallel": "no",
            "ncpus": 1,
            "RNGkind": "L'Ecuyer-CMRG",
            "order_seed": args.order_seed,
        },
        "source_sha256": source_hashes,
        "source_scope": "Workspace source fingerprints; installed bridge/package versions are separately recorded by the R runner.",
        "seeds": list(range(args.seed, args.seed + args.repeats)),
        "warmup_seeds": list(range(args.warmup_seed, args.warmup_seed + args.warmups)),
        "planned_order": plan,
        "inputs": {},
        "execution": [],
        "status": "running",
        "input_policy": "Separate regenerated CSVs with the main suite format"
        if args.generate_inputs
        else "Exact existing main-suite CSV files reused read-only",
        "cross_suite_comparison_caution": "Main and hybrid suites run at different wall-clock times; retain run order, settings and load limitations when comparing.",
    }
    # Verify every input before starting any timed task.
    for dataset in args.datasets:
        source = prepared_path(dataset, args.rows)
        metadata = json.loads(source.with_suffix(".json").read_text())
        npz_hash = file_hash(source)
        if npz_hash != metadata["npz_sha256"] or metadata["shape"][0] != args.rows:
            raise ValueError(f"Prepared NPZ hash/row count does not match metadata: {dataset}")
        csv_dir = args.output_dir / "inputs" if args.generate_inputs else args.csv_dir
        if args.generate_inputs:
            generate_csvs(source, dataset, csv_dir)
        paths = {name: csv_dir / f"{dataset}-{name}.csv" for name in ("input", "truth", "mask")}
        csv_metadata = {
            name: inspect_csv(path, args.rows, metadata["columns"]) for name, path in paths.items()
        }
        suite["inputs"][dataset] = {
            "npz_filename": source.name,
            "npz_sha256": npz_hash,
            "shape": metadata["shape"],
            "csv": csv_metadata,
            "source_archive_sha256": metadata["source_archive_sha256"],
        }
    save_suite(suite_path, suite)
    active_entry = None
    try:
        for task in plan:
            changed_sources = [
                str(path.relative_to(ROOT))
                for path in sources
                if not path.exists() or file_hash(path) != source_hashes[str(path.relative_to(ROOT))]
            ]
            if changed_sources:
                suite["status"] = "failed"
                suite["aborted_reason"] = "workspace_sources_changed_after_initial_fingerprint"
                suite["changed_sources"] = changed_sources
                suite["all_requested_tasks_succeeded"] = False
                save_suite(suite_path, suite)
                return 2
            dataset, method = task["dataset"], task["method"]
            output = args.output_dir / f"{dataset}-{method}.json"
            config_path = args.output_dir / f"{dataset}-{method}.config.json"
            log_path = args.output_dir / f"{dataset}-{method}.log"
            if any(path.exists() for path in (output, config_path, log_path)):
                raise FileExistsError(f"Refusing to overwrite previous hybrid task: {dataset}/{method}")
            csv_dir = args.output_dir / "inputs" if args.generate_inputs else args.csv_dir
            config = {
                **{
                    f"{name}_csv": str((csv_dir / f"{dataset}-{name}.csv").absolute())
                    for name in ("input", "truth", "mask")
                },
                "output_json": str(output.absolute()),
                "m": args.m,
                "seeds": suite["seeds"],
                "warmups": args.warmups,
                "warmup_seed": args.warmup_seed,
                "parallel": "no",
                "ncpus": 1,
                "threads": args.threads,
                "device": task["device"],
                "dtype": task["dtype"],
                "tolerance": 1e-4,
                "emburn": [0, args.max_iterations],
                "empri": None,
                "autopri": 0.05,
                "startvals": 0,
                "boot.type": "ordinary",
                "provenance": {"input": suite["inputs"][dataset], "source_sha256": source_hashes},
            }
            config_path.write_text(json.dumps(config, indent=2) + "\n")
            environment = os.environ.copy()
            environment.update({key: str(args.threads) for key in THREAD_VARIABLES})
            environment["RETICULATE_PYTHON"] = sys.executable  # Preserve the venv executable symlink.
            environment["PYTORCH_ENABLE_MPS_FALLBACK"] = "0"
            print(f"Starting hybrid R pipeline: {dataset} / {method}", flush=True)
            entry = {
                "dataset": dataset,
                "method": method,
                "device": task["device"],
                "dtype": task["dtype"],
                "result": output.name,
                "log": log_path.name,
                "started_utc": datetime.now(UTC).isoformat(),
                "status": "running",
                "exit_status": None,
            }
            active_entry = entry
            suite["execution"].append(entry)
            save_suite(suite_path, suite)
            with log_path.open("x") as log:
                try:
                    result = subprocess.run(
                        [
                            args.rscript,
                            str(ROOT / "scripts/benchmark_hybrid.R"),
                            str(config_path.absolute()),
                        ],
                        cwd=ROOT,
                        env=environment,
                        stdout=log,
                        stderr=subprocess.STDOUT,
                        timeout=args.timeout_seconds,
                        check=False,
                    )
                    entry["exit_status"] = result.returncode
                    entry["status"] = "completed" if result.returncode == 0 else "failed"
                except subprocess.TimeoutExpired:
                    entry.update(
                        {
                            "exit_status": None,
                            "status": "timeout",
                            "timeout_seconds": args.timeout_seconds,
                        }
                    )
                except OSError as error:
                    entry.update(
                        {
                            "exit_status": None,
                            "status": "launch_failed",
                            "error_type": type(error).__name__,
                        }
                    )
            entry["finished_utc"] = datetime.now(UTC).isoformat()
            entry["source_unchanged_during_process"] = all(
                path.exists() and file_hash(path) == source_hashes[str(path.relative_to(ROOT))]
                for path in sources
            )
            if not entry["source_unchanged_during_process"]:
                entry["status"] = "workspace_source_changed"
            entry["report_exists"] = output.exists()
            if output.exists():
                report = json.loads(output.read_text())
                entry["all_requested_runs_succeeded"] = report.get("summary", {}).get(
                    "all_requested_runs_succeeded", False
                )
                entry["report_sha256"] = file_hash(output)
            else:
                entry["all_requested_runs_succeeded"] = False
            save_suite(suite_path, suite)
            print(f"Finished {dataset} / {method}: {entry['status']}", flush=True)
            active_entry = None
    except (KeyboardInterrupt, Exception) as error:  # noqa: BLE001 - retain partial task evidence
        interrupted = isinstance(error, KeyboardInterrupt)
        state = "interrupted" if interrupted else "failed"
        if active_entry is not None:
            active_entry.update(status=state, error_type=type(error).__name__,
                                finished_utc=datetime.now(UTC).isoformat())
        suite.update(status=state, aborted_reason="keyboard_interrupt" if interrupted else "runner_error",
                     error_type=type(error).__name__, all_requested_tasks_succeeded=False,
                     updated_utc=datetime.now(UTC).isoformat())
        save_suite(suite_path, suite)
        return 130 if interrupted else 1
    suite["completed_utc"] = datetime.now(UTC).isoformat()
    suite["all_requested_tasks_succeeded"] = all(
        entry["status"] == "completed" and entry["all_requested_runs_succeeded"]
        for entry in suite["execution"]
    )
    suite["status"] = "completed" if suite["all_requested_tasks_succeeded"] else "failed"
    save_suite(suite_path, suite)
    return 0 if suite["all_requested_tasks_succeeded"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
